on:
  issue_comment:
    types:
      - created

name: Add Labels to PR

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      # 检查代码仓库
      - name: Checkout code
        uses: actions/checkout@v3

      # 从评论中提取并格式化标签为 "用户名: 标签"
      - name: Extract reviewer and labels
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/') }}
        id: extract_labels
        run: |
          comment_body="${{ github.event.comment.body }}"
          reviewer="${{ github.event.comment.user.login }}"
          raw_labels=$(echo "$comment_body" | sed 's|^/||')
          formatted_labels=$(echo "$raw_labels" | awk -v reviewer="$reviewer" '{split($0, arr, ","); for (i in arr) {gsub(/^ +| +$/, "", arr[i]); print reviewer ": " arr[i]}}')
          echo "Formatted labels: $formatted_labels"
          echo "::set-output name=labels::$formatted_labels"

      # 将提取的标签添加到 PR
      - name: Add labels via PR comment
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.extract_labels.outputs.labels }}
