on:
  pull_request:
    types:
      - opened
  issue_comment:
    types:
      - created

name: Add Labels to PR

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug event context
        run: echo "${{ toJson(github.event) }}"

      - name: Print PR number
        if: ${{ github.event.pull_request }}
        run: echo "PR number: ${{ github.event.pull_request.number }}"

      - name: Add default labels on PR creation
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true

      - name: Extract labels from comment
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/') }}
        id: extract_labels
        run: |
          labels=$(echo "${{ github.event.comment.body }}" | sed 's|^/||')
          echo "Extracted labels: $labels"
          echo "::set-output name=labels::$labels"

      - name: Add labels via PR comment
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.extract_labels.outputs.labels }}
