name: Add Labels to PR

on:
  # 监听 PR 创建事件
  pull_request:
    types:
      - opened

  # 监听 PR 评论事件
  issue_comment:
    types:
      - created

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      # 检查代码仓库
      - name: Checkout code
        uses: actions/checkout@v3

      # 对 PR 创建时添加默认标签
      - name: Add default labels on PR creation
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ github.base_ref }}

      # 对 PR 评论中以 / 开头的命令动态添加标签
      - name: Add labels via PR comment
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ github.event.comment.body.substring(1) }}
