on:
  push:
    branches:
      - 'pr@**'
      - 'repr@**'

name: demo 自动创建 PR

jobs:
  generic_handler:
    name: 自动创建 PR
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
